### ISSUE TITLE
Confi enviroment errors. Hot Fix. Log below

### ISSUE THREAD

**Issue by Phuc-code-2001** [Phuc-code-2001/Dental-Clinic-Management#17]
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_7b452ffc/manage.py", line 22, in <module>
           main()
         File "/tmp/build_7b452ffc/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
           django.setup()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/app/.heroku/python/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
           app_config.import_models()
         File "/app/.heroku/python/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
           self.models_module = import_module(models_module_name)
         File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
         File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 883, in exec_module
         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
         File "/tmp/build_7b452ffc/profiles/models.py", line 7, in <module>
           from .imagekit import file_upload, file_delete, DEFAULT_IMAGE
         File "/tmp/build_7b452ffc/profiles/imagekit.py", line 17, in <module>
           imagekit = ImageKit(
         File "/app/.heroku/python/lib/python3.10/site-packages/imagekitio/client.py", line 24, in __init__
           self.ik_request = ImageKitRequest(
         File "/app/.heroku/python/lib/python3.10/site-packages/imagekitio/resource.py", line 30, in __init__
           raise ValueError(ERRORS.MANDATORY_INITIALIZATION_MISSING.value)
       ValueError: {'message': 'Missing public_key or private_key or url_endpoint during ImageKit initialization', Type help() for interactive help, or help(object) for help about object.: ''}
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by Phuc-code-2001** [comment]
Forgot config vars on heroku.
